version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "App is running"
      - run:
          name: Install libs
          command: sudo apt-get install libxtst6 libgconf-2-4 libnss3 libasound2 libgtk-3-0 libxss1
      - run: npm install
      - run: CI=false npm run build
      - run:
          name: Deploy
          command: curl -X POST -d {} https://api.netlify.com/build_hooks/5f03f431e7992f7e665e2de5
workflows:
    build-and-test:
      jobs:
        - build-and-test